/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.zcu.kiv.cacheSimulator.gui;

import cz.zcu.kiv.cacheSimulator.cachePolicies.FBR;

/**
 *
 * @author Pavel Bzoch
 * trida pro nastaveni FBR policy
 */
@SuppressWarnings("serial")
public class FBRPanel extends javax.swing.JPanel {

    /**
     * Creates new form FBRPanel
     */
    public FBRPanel() {
        initComponents();
        OLDSpinner.setValue((int)((FBR.getOLD_SECTION() * 100)));
        NEWSpinner.setValue((int) (FBR.getNEW_SECTION() * 100));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        FBRLabel = new javax.swing.JLabel();
        oldLabel = new javax.swing.JLabel();
        NewLabel = new javax.swing.JLabel();
        OLDSpinner = new javax.swing.JSpinner();
        NEWSpinner = new javax.swing.JSpinner();

        FBRLabel.setText("FBR settings");

        oldLabel.setText("% of cache capacity for OLD section:");

        NewLabel.setText("% of cache capacity for NEW section:");

        OLDSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                OLDSpinnerStateChanged(evt);
            }
        });

        NEWSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                NEWSpinnerStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NewLabel)
                    .addComponent(oldLabel)
                    .addComponent(FBRLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NEWSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OLDSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(FBRLabel)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oldLabel)
                    .addComponent(OLDSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewLabel)
                    .addComponent(NEWSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(151, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    private void OLDSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_OLDSpinnerStateChanged
        if ((Integer)OLDSpinner.getValue() <= 0){
            OLDSpinner.setValue(1);
        }
        if ((Integer)NEWSpinner.getValue() + (Integer)OLDSpinner.getValue() >=100){
            OLDSpinner.setValue(100 - (Integer)NEWSpinner.getValue());
        }
        FBR.setOLD_SECTION(((Integer)OLDSpinner.getValue() / 100.0));
    }//GEN-LAST:event_OLDSpinnerStateChanged

    private void NEWSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_NEWSpinnerStateChanged
        if ((Integer)NEWSpinner.getValue() <= 0){
            NEWSpinner.setValue(1);
        }
        if ((Integer)NEWSpinner.getValue() + (Integer)OLDSpinner.getValue() >=100){
            NEWSpinner.setValue(100 - (Integer)OLDSpinner.getValue());
        }
        FBR.setNEW_SECTION(((Integer)NEWSpinner.getValue() / 100.0));
    }//GEN-LAST:event_NEWSpinnerStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FBRLabel;
    private javax.swing.JSpinner NEWSpinner;
    private javax.swing.JLabel NewLabel;
    private javax.swing.JSpinner OLDSpinner;
    private javax.swing.JLabel oldLabel;
    // End of variables declaration//GEN-END:variables
}
