/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.zcu.kiv.cacheSimulator.gui;

import javax.swing.SpinnerNumberModel;

import cz.zcu.kiv.cacheSimulator.cachePolicies.LRFU;

/**
 *
 * @author Pavel Bzoch
 * trida pro nastaveni LRFU policy
 */
@SuppressWarnings("serial")
public class LRFUPanel extends javax.swing.JPanel {

    /**
     * Creates new form LRFUPanel
     */
    public LRFUPanel() {
        initComponents();
        SpinnerNumberModel pModel = new SpinnerNumberModel(LRFU.getP(), 1, 10, 0.1);
        pSpinner.setModel(pModel);
        SpinnerNumberModel lambdaModel = new SpinnerNumberModel(LRFU.getLAMBDA(), 0, 10, 0.01);
        lambdaSpinner.setModel(lambdaModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        lrfuLabel = new javax.swing.JLabel();
        PLabel = new javax.swing.JLabel();
        lambdaLabel = new javax.swing.JLabel();
        pSpinner = new javax.swing.JSpinner();
        lambdaSpinner = new javax.swing.JSpinner();

        lrfuLabel.setText("LRFU settings");

        PLabel.setText("P:");

        lambdaLabel.setText("Lambda:");

        pSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                pSpinnerStateChanged(evt);
            }
        });

        lambdaSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                lambdaSpinnerStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(lrfuLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lambdaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lambdaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(pSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lrfuLabel)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PLabel)
                    .addComponent(pSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lambdaLabel)
                    .addComponent(lambdaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(137, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    private void pSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_pSpinnerStateChanged
        LRFU.setP((Double)pSpinner.getValue());
    }//GEN-LAST:event_pSpinnerStateChanged

    private void lambdaSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_lambdaSpinnerStateChanged
        LRFU.setLAMBDA((Double) lambdaSpinner.getValue());
    }//GEN-LAST:event_lambdaSpinnerStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PLabel;
    private javax.swing.JLabel lambdaLabel;
    private javax.swing.JSpinner lambdaSpinner;
    private javax.swing.JLabel lrfuLabel;
    private javax.swing.JSpinner pSpinner;
    // End of variables declaration//GEN-END:variables
}
