/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.zcu.kiv.cacheSimulator.gui;

import cz.zcu.kiv.cacheSimulator.cachePolicies.LRU_K;

/**
 *
 * @author Pavel Bzoch
 * trida pro nastaveni LRU_K policy
 */
@SuppressWarnings("serial")
public class LRU_KPanel extends javax.swing.JPanel {

    /**
     * Creates new form LRU_KPanel
     */
    public LRU_KPanel() {
        initComponents();
        kSpinner.setValue(LRU_K.getK());
        periodSpinner.setValue(LRU_K.getCORRELATED_REFERENCE_PERIOD());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     private void initComponents() {

        lru_kLabel = new javax.swing.JLabel();
        kLabel = new javax.swing.JLabel();
        periodLabel = new javax.swing.JLabel();
        kSpinner = new javax.swing.JSpinner();
        periodSpinner = new javax.swing.JSpinner();

        lru_kLabel.setText("LRU-K settings");

        kLabel.setText("K:");

        periodLabel.setText("Corelated reference period:");

        kSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                kSpinnerStateChanged(evt);
            }
        });

        periodSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                periodSpinnerStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(kLabel)
                        .addGap(92, 92, 92))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(periodLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(periodSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 94, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(lru_kLabel)
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(lru_kLabel)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kLabel)
                    .addComponent(kSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(periodLabel)
                    .addComponent(periodSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(126, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    private void kSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_kSpinnerStateChanged
        if ((Integer)kSpinner.getValue() <=0)
            kSpinner.setValue(1);
        else if ((Integer)kSpinner.getValue() > 10){
            kSpinner.setValue(10);
        }
        LRU_K.setK((Integer)kSpinner.getValue());
    }//GEN-LAST:event_kSpinnerStateChanged

    private void periodSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_periodSpinnerStateChanged
        if ((Integer)periodSpinner.getValue() <=0)
            periodSpinner.setValue(1);
        else if ((Integer)periodSpinner.getValue() > 30){
            periodSpinner.setValue(30);
        }
        LRU_K.setCORRELATED_REFERENCE_PERIOD((Integer)periodSpinner.getValue());
    }//GEN-LAST:event_periodSpinnerStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel kLabel;
    private javax.swing.JSpinner kSpinner;
    private javax.swing.JLabel lru_kLabel;
    private javax.swing.JLabel periodLabel;
    private javax.swing.JSpinner periodSpinner;
    // End of variables declaration//GEN-END:variables
}
