/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.zcu.kiv.cacheSimulator.gui;

import cz.zcu.kiv.cacheSimulator.cachePolicies.FBR;

/**
 *
 * @author Pavel Bzoch
 * trida pro nastaveni FBR policy
 */
@SuppressWarnings("serial")
public class FBRPanel extends javax.swing.JPanel {

    /**
     * Creates new form FBRPanel
     */
    public FBRPanel() {
        initComponents();
        this.OLDSpinner.setValue((int)((FBR.getOLD_SECTION() * 100)));
        this.NEWSpinner.setValue((int) (FBR.getNEW_SECTION() * 100));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        this.FBRLabel = new javax.swing.JLabel();
        this.oldLabel = new javax.swing.JLabel();
        this.NewLabel = new javax.swing.JLabel();
        this.OLDSpinner = new javax.swing.JSpinner();
        this.NEWSpinner = new javax.swing.JSpinner();

        this.FBRLabel.setText("FBR settings");

        this.oldLabel.setText("% of cache capacity for OLD section:");

        this.NewLabel.setText("% of cache capacity for NEW section:");

        this.OLDSpinner.addChangeListener(this::OLDSpinnerStateChanged);
        this.NEWSpinner.addChangeListener(this::NEWSpinnerStateChanged);

        final javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(this.NewLabel)
                    .addComponent(this.oldLabel)
                    .addComponent(this.FBRLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(this.NEWSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(this.OLDSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(this.FBRLabel)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(this.oldLabel)
                    .addComponent(this.OLDSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(this.NewLabel)
                    .addComponent(this.NEWSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(151, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    private void OLDSpinnerStateChanged(final javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_OLDSpinnerStateChanged
        if ((Integer) this.OLDSpinner.getValue() <= 0){
            this.OLDSpinner.setValue(1);
        }
        if ((Integer) this.NEWSpinner.getValue() + (Integer) this.OLDSpinner.getValue() >=100){
            this.OLDSpinner.setValue(100 - (Integer) this.NEWSpinner.getValue());
        }
        FBR.setOLD_SECTION(((Integer) this.OLDSpinner.getValue() / 100.0));
    }//GEN-LAST:event_OLDSpinnerStateChanged

    private void NEWSpinnerStateChanged(final javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_NEWSpinnerStateChanged
        if ((Integer) this.NEWSpinner.getValue() <= 0){
            this.NEWSpinner.setValue(1);
        }
        if ((Integer) this.NEWSpinner.getValue() + (Integer) this.OLDSpinner.getValue() >=100){
            this.NEWSpinner.setValue(100 - (Integer) this.OLDSpinner.getValue());
        }
        FBR.setNEW_SECTION(((Integer) this.NEWSpinner.getValue() / 100.0));
    }//GEN-LAST:event_NEWSpinnerStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FBRLabel;
    private javax.swing.JSpinner NEWSpinner;
    private javax.swing.JLabel NewLabel;
    private javax.swing.JSpinner OLDSpinner;
    private javax.swing.JLabel oldLabel;
    // End of variables declaration//GEN-END:variables
}
