/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.zcu.kiv.cacheSimulator.gui;

import cz.zcu.kiv.cacheSimulator.shared.GlobalVariables;

/**
 *
 * @author Pavel Bzoch
 * trida pro nastaveni LFU with Server Statistics policy
 */
@SuppressWarnings("serial")
public class LFU_SSPanel extends javax.swing.JPanel {

    /**
     * Creates new form LFU_SSPavel
     */
    public LFU_SSPanel() {
        initComponents();
        this.lfuSendStatCheckBox.setSelected(GlobalVariables.isSendStatisticsToServerLFUSS());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        this.lfussSettingsLabel = new javax.swing.JLabel();
        this.lfuSendStatCheckBox = new javax.swing.JCheckBox();

        this.lfussSettingsLabel.setText("Settings for LFU with Server Statistics");

        this.lfuSendStatCheckBox.setText("Send statistics back to server");
        this.lfuSendStatCheckBox.addActionListener(this::lfuSendStatCheckBoxActionPerformed);

        final javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(this.lfuSendStatCheckBox)
                    .addComponent(this.lfussSettingsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(this.lfussSettingsLabel)
                .addGap(18, 18, 18)
                .addComponent(this.lfuSendStatCheckBox)
                .addContainerGap(191, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lfuSendStatCheckBoxActionPerformed(final java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lfuSendStatCheckBoxActionPerformed
        GlobalVariables.setSendStatisticsToServerLFUSS(this.lfuSendStatCheckBox.isSelected());
    }//GEN-LAST:event_lfuSendStatCheckBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox lfuSendStatCheckBox;
    private javax.swing.JLabel lfussSettingsLabel;
    // End of variables declaration//GEN-END:variables
}
