spring:
  application:
    name: '@project.artifactId@'

simulation:
  file-source:
    random-file-source:
      count-of-files: 100

cache:
  policy:
    fifo:
      capacity:
        min: 1024
        max: 100000000
        step: 1000
    lru:
      capacity:
        min: 1024
        max: 100000000
        step: 1000
    mru:
      capacity:
        min: 1024
        max: 100000000
        step: 1000
    rnd:
      capacity:
        min: 1024
        max: 100000000
        step: 1000
    2q:
      capacity:
        min: 1024
        max: 100000000
        step: 1000
      fifo-ratio: 0.5
    arc:
      capacity:
        min: 1024
        max: 100000000
        step: 1000
    clock:
      capacity:
        min: 1024
        max: 100000000
        step: 1000
    fbr:
      capacity:
        min: 1024
        max: 100000000
        step: 1000

logging:
  level:
    eu.qwsome: trace