spring:
  application:
    name: '@project.artifactId@'

simulation:
  file-source:
    random-file-source:
      count-of-files: 100

cache:
  policy:
    fifo:
      capacity:
        min: 1024
        max: 100000000
        step: 1000

logging:
  level:
    eu.qwsome: trace