/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.zcu.kiv.cacheSimulator.gui.configuration;

import cz.zcu.kiv.cacheSimulator.cachePolicies._2Q;

/**
 *
 * @author Pavel Bzoch
 * trida pro nastaveni 2Q policy
 */
@SuppressWarnings("serial")
public class _2QPanel extends javax.swing.JPanel {

    /**
     * Creates new form _2QPanel
     */
    public _2QPanel() {
        this.initComponents();
        this.fifocapSpinner.setValue((int) (_2Q.getFIFO_CAPACITY() * 100));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        this._2QjLabel = new javax.swing.JLabel();
        this.fifocapLabel = new javax.swing.JLabel();
        this.fifocapSpinner = new javax.swing.JSpinner();

        this._2QjLabel.setText("2 Queues settings");

        this.fifocapLabel.setText("%of cache capacity for FIFO:");

        this.fifocapSpinner.addChangeListener(evt -> _2QPanel.this.fifocapSpinnerStateChanged(evt));

        final javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(this._2QjLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(this.fifocapLabel)
                        .addGap(27, 27, 27)
                        .addComponent(this.fifocapSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(this._2QjLabel)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(this.fifocapLabel)
                    .addComponent(this.fifocapSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(189, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fifocapSpinnerStateChanged(final javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_fifocapSpinnerStateChanged
        if ((Integer)this.fifocapSpinner.getValue() <=0)
            this.fifocapSpinner.setValue(1);
        else if ((Integer)this.fifocapSpinner.getValue() > 75){
            this.fifocapSpinner.setValue(75);
        }
        _2Q.setFIFO_CAPACITY(((Integer)this.fifocapSpinner.getValue()) / 100.0);
    }//GEN-LAST:event_fifocapSpinnerStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel _2QjLabel;
    private javax.swing.JLabel fifocapLabel;
    private javax.swing.JSpinner fifocapSpinner;
    // End of variables declaration//GEN-END:variables
}
